sudo: false

language: node_js

env:
  global:
    - SAUCE_USERNAME='stasha'
    - SAUCE_ACCESS_KEY='f936ed34-7e11-4451-a627-faa923ec5adb'

matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "0.10"
      env: BROWSER=1
